### ISSUE TITLE
weibosearch  运行问题

### ISSUE THREAD

**Issue by shanshanpt** [chineking/cola#21]
start to get none
是网页没找到吗还是？还有weibosearch 中的.yaml没有配置keys，但是put_starts也没看到被调用呀，求指教一下啦，谢谢啦~~~

**Comment by chineking** [comment]
weibosearch will be rewrite by selenium opener. Selenium is obviously better solution to handle the dynamic webpage, besides, it just uses the real browser including firefox and chrome, thus it's much robust for robot detection.
