### ISSUE TITLE
cola近期的发布情况

### ISSUE THREAD

**Issue by hitalex** [chineking/cola#43]
请问作者近期有发布cola的计划么？cola一个release都还没有啊...

我最进在抓取微博，但是帐号被封的厉害，所以下一步打算加入多帐号登录功能，请问这个思路是否可行？

**Comment by fengkaijia** [comment]
可以指定哪个帐号给哪个worker吗？几个worker的IP所在地不同，开的登录保护也得不同。

**Comment by chineking** [comment]
@fengkaijia 

首先我不推荐这么做，worker之间是需要通信的，IP所在地不同可能有比较大的通信开销。
其次说一下worker下的instance登录帐号的选择原理。首先worker会按注册顺序排列，每个worker上有若干个instance，所以这所有的instance会有个编号，从0开始，到n_workers*n_instances-1。假设配置了N个帐号，那么instance从0开始会去取第0个帐号，第1个取第1个帐号，依次类推，其实是取模的操作。

所以假设你一定需要指定不同帐号，可以按instance顺序配置帐号。
