### ISSUE TITLE
Name or Service not known

### ISSUE THREAD

**Issue by jlovedragon** [chineking/cola#45]
我启动了mongod.配置了wiki.yaml，都是用的localhost和27017，但还是出现socket.gaierror: [Errno -2] Name or service not known，请教下是什么原因～

**Comment by jlovedragon** [comment]
我使用的是dev版本，系统用的是Archlinux

**Comment by chineking** [comment]
mongo能连上么？mongo命令

2015-01-09 14:36 GMT+08:00 徐风轻吟 <notifications@github.com>:

> 我使用的是dev版本，系统用的是Archlinux
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chineking/cola/issues/45#issuecomment-69298947>.
>



-- 
秦续业（Chine King）
---------------------------------
>>Tel：+86-18616109836
>>QQ：344861256
>>E-mail：qin@qinxuye.me <chinekingseu@gmail.com>
>>http://qinxuye.me

**Comment by jlovedragon** [comment]
用mongo命令是可以连上的

**Comment by jlovedragon** [comment]
mongod的输出：
2015-01-09T14:56:38.660+0800 [initandlisten] waiting for connections on port 27017
2015-01-09T14:56:41.823+0800 [initandlisten] connection accepted from 127.0.0.1:46465 #1 (1 connection now open)
mongo的输出：
quentin@laptop /data/db % mongo
MongoDB shell version: 2.6.6
connecting to: test

**Comment by jlovedragon** [comment]
附上wiki.yaml的配置：
job:
  db: wiki
  mode: url # also can be `bundle`
  size: 100   # the destination (including bundle or url) size
  limit: 0  # 0 means no restrictions, if greater than 0, means webpages opened per minute.
  master_port: 12102
  port: 12103
  instances: 2
  mongo:
    host: localhost
    port: 27017
  starts:
    - url: http://en.wikipedia.org/wiki/Python
    - url: http://zh.wikipedia.org/wiki/Python

**Comment by chineking** [comment]
把完整的终端错误输出贴出来看看呢

2015-01-09 15:02 GMT+08:00 徐风轻吟 <notifications@github.com>:

> 附上wiki.yaml的配置：
> job:
> db: wiki
> mode: url # also can be bundle
> size: 100 # the destination (including bundle or url) size
> limit: 0 # 0 means no restrictions, if greater than 0, means webpages
> opened per minute.
> master_port: 12102
> port: 12103
> instances: 2
> mongo:
> host: localhost
> port: 27017
> starts:
> - url: http://en.wikipedia.org/wiki/Python
> - url: http://zh.wikipedia.org/wiki/Python
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chineking/cola/issues/45#issuecomment-69300521>.
>



-- 
秦续业（Chine King）
---------------------------------
>>Tel：+86-18616109836
>>QQ：344861256
>>E-mail：qin@qinxuye.me <chinekingseu@gmail.com>
>>http://qinxuye.me

**Comment by jlovedragon** [comment]
Traceback (most recent call last):
  File "__init__.py", line 160, in <module>
    load_job(os.path.dirname(os.path.abspath(__file__)))
  File "/home/quentin/git/cola/cola/worker/loader.py", line 472, in load_job
    with StandaloneWorkerJobLoader(job, root, force=force) as job_loader:
  File "/home/quentin/git/cola/cola/worker/loader.py", line 355, in __init__
    local=local, nodes=nodes, copies=copies, force=force)
  File "/home/quentin/git/cola/cola/worker/loader.py", line 92, in __init__
    self.init_rpc_server()
  File "/home/quentin/git/cola/cola/job/loader.py", line 59, in init_rpc_server
    rpc_server = ColaRPCServer((self.host, self.port))
  File "/home/quentin/git/cola/cola/core/rpc.py", line 34, in __init__
    SimpleXMLRPCServer.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/SimpleXMLRPCServer.py", line 593, in __init__
    SocketServer.TCPServer.__init__(self, addr, requestHandler, bind_and_activate)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno -2] Name or service not known

**Comment by chineking** [comment]
这个不是mongo的问题，应该是启动RPC服务器的时候，绑定本地ip和端口报错了。

如果只使用单机模式，可以暂时使用develop版本，单机模式下默认不会启动RPC服务器。

分布式模式下可以指定ip地址。

**Comment by chineking** [comment]
问题有解决吗

**Comment by jlovedragon** [comment]
嗯，昨天晚上搞定了，主要原因是checkout develop分支时我输入的是checkout dev，所以没有正确的切换到develop分支，单机已经没问题了，不过爬取一段时间后发现会出现ip受限要如验证码的问题，目前正在尝试用代理ip，多谢你了～

**Comment by chineking** [comment]
ok，有问题再讨论。先close这个issue
