### ISSUE TITLE
json.loads(br.response().read())["data"]

### ISSUE THREAD

**Issue by laokongzhuang** [chineking/cola#46]
如果br.response().read()读取数据失败的话，这个会产生错误，是不是应该加上异常处理？

**Comment by chineking** [comment]
cola中，一个parser的错误会被捕捉到，会分为几种情况
1）服务器错误
2）网络错误
3）其他

这些error的处理方式不同主要区别在于重试的次数和间隔的不同（根据配置）。

对于你说的错误，上层会被cola给捕捉，并重试一定次数。

如果用户想自己处理异常，在parser中做就可以了。
