### ISSUE TITLE
爬取follow列表的问题

### ISSUE THREAD

**Issue by baduni** [chineking/cola#57]
你好。请问：
爬取的follow列表里的用户数，好像最大是100个，不知是否是有此限制？
另外，可否设置只爬取用户个人信息，而不爬取用户的微博？

**Comment by chineking** [comment]
100个是新浪微博的设置，如果你和抓取用户不是好友关系（互粉），你只能看到10页的内容，这个网页上尝试就知道了。

只抓取信息可以的，不过需要改下代码，修改bundle.py，可以看到几个url，把微博相关的注释掉，也就是有mbloglist那个。

**Comment by baduni** [comment]
原来是新浪的限制。。。
改好了，可行。代码写得好啊，虽然我看着挺晕。谢了。
