### ISSUE TITLE
不太明白weibo.yaml里面的部分配置，有详细的一对一解释吗？

### ISSUE THREAD

**Issue by xiaoleihuang** [chineking/cola#62]
mongo:
     host: localhost
     port: 27017
   login:
     - username:  # username
       password:  # password
   starts:
     - uid: 3211200050
     - uid: 1898353550
   fetch:
     forward: yes
     comment: yes
     like: yes
   clear: yes
这些字面上能懂，其他的部分请问有解释吗？

不太明白weibo.yaml里面的部分配置，有详细的一对一解释吗？

**Comment by chineking** [comment]
job:
  db: sina # 数据库名称
  mode: bundle # bundle模式，这个可以参考wiki
  size: 100   # 目标抓取的个数
  speed: 
    max: -1  # 每分钟最多抓取的网页个数，对于集群，单机模式就是本机，-1是不限制
    single: -1 # 每个instance每分钟最多抓去的网页个数
    adaptive: no # 自适应地控制抓取速度，实验功能
  instances: 2  # 启动的线程数
  priorities: 3 # 有多少个优先队列，不同的用户可以设置不同优先级，app里应该没分，可以设成1
  copies: 1 # 冗余的数据份数，可以设成0
  inc: yes  # 是否增量抓取数据，不需要的话设成no，yes的话任务不会主动结束，会一直重复抓取更新
  shuffle: no # 每次抓取前，把抓取url列表打乱，只在bundle模式下用
  error:
    network:  # 网络异常
      retries: -1 # 0 means no retry, -1 means keeping on trying
      span: 20 # seconds span to retry
      ignore: no # only work under bundle mode, if True will ignore this url and move to the next after several tries, or move to the next bundle
    server: # like 404 or 500 error returned by server
      retries: 5
      span: 10
      ignore: no
  components:
    deduper:
      cls: cola.core.dedup.FileBloomFilterDeduper
  mongo:
    host: localhost
    port: 27017
  login:
    - username: # username
      password: # password
  starts:
    - uid: 3211200050
    - uid: 1898353550
  fetch:
    forward: no
    comment: no
    like: no
  clear: no

**Comment by xiaoleihuang** [comment]
@chineking Thank you!
